apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyverno-artifact-operator.fullname" . }}-controller-manager
  namespace: {{ include "kyverno-artifact-operator.namespace" . }}
  labels:
    {{- include "kyverno-artifact-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kyverno-artifact-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kyverno-artifact-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyverno-artifact-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.controller.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        - --health-probe-bind-address=:8081
        env:
        - name: WATCHER_IMAGE
          value: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag }}"
        - name: WATCHER_SERVICE_ACCOUNT
          value: {{ include "kyverno-artifact-operator.watcherServiceAccountName" . }}
        - name: WATCHER_SECRET_NAME
          value: {{ .Values.watcher.secret.name }}
        - name: GITHUB_TOKEN_KEY
          value: {{ .Values.watcher.secret.githubTokenKey }}
        - name: ARTIFACTORY_USERNAME_KEY
          value: {{ .Values.watcher.secret.artifactoryUsernameKey }}
        - name: ARTIFACTORY_PASSWORD_KEY
          value: {{ .Values.watcher.secret.artifactoryPasswordKey }}
        ports: []
        livenessProbe:
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
