apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kyverno-artifact-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "kyverno-artifact-operator.namespace" . }}
  labels:
    {{- include "kyverno-artifact-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kyverno-artifact-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "kyverno-artifact-operator.serviceAccountName" . }}
  namespace: {{ include "kyverno-artifact-operator.namespace" . }}
