{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyverno-artifact-operator.serviceAccountName" . }}
  namespace: {{ include "kyverno-artifact-operator.namespace" . }}
  labels:
    {{- include "kyverno-artifact-operator.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.watcher.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyverno-artifact-operator.watcherServiceAccountName" . }}
  namespace: {{ include "kyverno-artifact-operator.namespace" . }}
  labels:
    {{- include "kyverno-artifact-operator.labels" . | nindent 4 }}
{{- end }}
